//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradoviTbl
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public Nullable<int> DrzavaId { get; set; }
        public Nullable<bool> ImaOpstine { get; set; }
    }
}
