//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skomi69_dostavaEntities3 : DbContext
    {
        public skomi69_dostavaEntities3()
            : base("name=skomi69_dostavaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CommantTbl> CommantTbls { get; set; }
        public virtual DbSet<DrzavaTbl> DrzavaTbls { get; set; }
        public virtual DbSet<GradoviTbl> GradoviTbls { get; set; }
        public virtual DbSet<Star> Stars { get; set; }
        public virtual DbSet<Veza_Grad_OpstinaTbl> Veza_Grad_OpstinaTbl { get; set; }
        public virtual DbSet<KuhinjeTbl> KuhinjeTbls { get; set; }
        public virtual DbSet<RestoranTbl> RestoranTbls { get; set; }
        public virtual DbSet<OpstineTbl> OpstineTbls { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
