//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestoranTbl
    {
        public int RestoranID { get; set; }
        public string Ime { get; set; }
        public string Logo { get; set; }
        public string Koordinate { get; set; }
        public decimal MinimalnaNarudzbina { get; set; }
        public bool DostavaSeNaplacuje { get; set; }
        public decimal Ocena { get; set; }
        public Nullable<int> KuhinjaId { get; set; }
    
        public virtual KuhinjeTbl KuhinjeTbl { get; set; }
    }
}
