//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veza_Grad_OpstinaTbl
    {
        public int RestoranId { get; set; }
        public Nullable<int> GradId { get; set; }
        public Nullable<int> OpstinaId { get; set; }
        public Nullable<bool> IsDelivering { get; set; }
    }
}
